AWSTemplateFormatVersion: "2010-09-09"
Description: "CRC clean build – S3-only skeleton"

Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  SiteBucketName:
    Description: "S3 bucket name"
    Value: !Ref SiteBucket
