AWSTemplateFormatVersion: "2010-09-09"
Description: "CRC clean build – S3-only skeleton"

Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-oac"
        Description: OAC for CloudFront access to private S3 origin
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4
      Tags:
        - Key: Project
          Value: aws-crc-clean-build
        - Key: Component
          Value: cloudfront-oac
        - Key: Layer
          Value: edge

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html

        Origins:
          - Id: S3Origin
            DomainName: !GetAtt SiteBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOAC
            S3OriginConfig: {}

        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false

        PriceClass: PriceClass_100

Outputs:
  SiteBucketName:
    Description: "S3 bucket name"
    Value: !Ref SiteBucket

  CloudFrontDomainName:
    Description: "CloudFront distribution domain"
    Value: !GetAtt CloudFrontDistribution.DomainName
