AWSTemplateFormatVersion: "2010-09-09"
Description: "CRC clean build – S3-only skeleton"

Resources:
  CfnDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: crc-clean-build-gha-deploy-role-cfn
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub "arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com"
            Action: "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: "repo:timjosmith/aws-crc-clean-build:ref:refs/heads/main"
      Policies:
        - PolicyName: PassExecutionRole
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: AllowPassCfnExecutionRole
                Effect: Allow
                Action: iam:PassRole
                Resource: arn:aws:iam::401907937551:role/crc-clean-build-cfn-exec
        - PolicyName: CloudFormationLifecycle
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: CloudFormationLifecycle
                Effect: Allow
                Action:
                  - cloudformation:ValidateTemplate
                  - cloudformation:CreateStack
                  - cloudformation:UpdateStack
                  - cloudformation:DeleteStack
                  - cloudformation:CreateChangeSet
                  - cloudformation:ExecuteChangeSet
                  - cloudformation:DescribeStacks
                  - cloudformation:DescribeStackEvents
                  - cloudformation:DescribeChangeSet
                  - cloudformation:GetTemplateSummary
                  - cloudformation:ListStacks
                Resource: "*"

  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  SiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontReadOnlyFromThisDistribution
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action:
              - s3:GetObject
            Resource: !Sub "${SiteBucket.Arn}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}"

  VisitorCounterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: crc-visitor-counter
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: CounterName
          AttributeType: S
      KeySchema:
        - AttributeName: CounterName
          KeyType: HASH
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      DeletionProtectionEnabled: true

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-oac"
        Description: OAC for CloudFront access to private S3 origin
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: index.html
        Aliases:
          - crc.timjosmith.com

        Origins:
          - Id: S3Origin
            DomainName: !GetAtt SiteBucket.RegionalDomainName
            OriginAccessControlId: !Ref CloudFrontOAC
            S3OriginConfig: { }

        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          ForwardedValues:
            QueryString: false

        PriceClass: PriceClass_100

        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-1:401907937551:certificate/2b71e9cd-4bd3-49f5-849f-c89c3b5e087d
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

      Tags:
        - Key: Project
          Value: aws-crc-clean-build
        - Key: Component
          Value: cloudfront-distribution
        - Key: Layer
          Value: edge

Outputs:
  SiteBucketName:
    Description: "S3 bucket name"
    Value: !Ref SiteBucket

  VisitorCounterTableName:
    Description: "Visitor counter DynamoDB table"
    Value: !Ref VisitorCounterTable

  CloudFrontDomainName:
    Description: "CloudFront distribution domain"
    Value: !GetAtt CloudFrontDistribution.DomainName
